//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WizFDS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wizFDS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        #region Default icons

        internal static System.Drawing.Bitmap defaultIco {
            get {
                object obj = ResourceManager.GetObject("defaultIco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap defaultIcoLarge {
            get {
                object obj = ResourceManager.GetObject("defaultIcoLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }


        #endregion

        #region CFAST icons

        internal static System.Drawing.Bitmap corridorLarge {
            get {
                object obj = ResourceManager.GetObject("corridorLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap staircaseLarge {
            get {
                object obj = ResourceManager.GetObject("staircaseLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap door {
            get {
                object obj = ResourceManager.GetObject("door", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap doorLarge {
            get {
                object obj = ResourceManager.GetObject("doorLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap windowLarge {
            get {
                object obj = ResourceManager.GetObject("windowLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap inletLarge {
            get {
                object obj = ResourceManager.GetObject("inletLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap holeLarge {
            get {
                object obj = ResourceManager.GetObject("holeLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap vent {
            get {
                object obj = ResourceManager.GetObject("vent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap holeaut {
            get {
                object obj = ResourceManager.GetObject("holeaut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }


        #endregion

        #region FDS Geometry icons

        internal static System.Drawing.Bitmap obstLarge {
            get {
                object obj = ResourceManager.GetObject("obstLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ceiling {
            get {
                object obj = ResourceManager.GetObject("ceiling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap cwall {
            get {
                object obj = ResourceManager.GetObject("cwall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap meshLarge {
            get {
                object obj = ResourceManager.GetObject("meshLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap meshAutoLarge {
            get {
                object obj = ResourceManager.GetObject("meshAutoLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap openLarge {
            get {
                object obj = ResourceManager.GetObject("openLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wall {
            get {
                object obj = ResourceManager.GetObject("wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap wallLarge {
            get {
                object obj = ResourceManager.GetObject("wallLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap geom {
            get {
                object obj = ResourceManager.GetObject("geom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap geomLarge {
            get {
                object obj = ResourceManager.GetObject("geomLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap geomMan {
            get {
                object obj = ResourceManager.GetObject("geomMan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap geomManLarge {
            get {
                object obj = ResourceManager.GetObject("geomManLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        #endregion

        #region FDS Fire & Ventilation & Output icons 

        internal static System.Drawing.Bitmap ventLarge {
            get {
                object obj = ResourceManager.GetObject("ventLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap jetfanLarge {
            get {
                object obj = ResourceManager.GetObject("jetfanLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap fireLarge {
            get {
                object obj = ResourceManager.GetObject("fireLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap deviceLarge {
            get {
                object obj = ResourceManager.GetObject("deviceLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap sliceLarge {
            get {
                object obj = ResourceManager.GetObject("sliceLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }


        #endregion

        #region Layers
        internal static System.Drawing.Bitmap layerOffLarge {
            get {
                object obj = ResourceManager.GetObject("layerOffLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap layerOnLarge {
            get {
                object obj = ResourceManager.GetObject("layerOnLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap layersLarge {
            get {
                object obj = ResourceManager.GetObject("layersLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap levelAdd {
            get {
                object obj = ResourceManager.GetObject("levelAdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap levelHide {
            get {
                object obj = ResourceManager.GetObject("levelHide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap levelShow {
            get {
                object obj = ResourceManager.GetObject("levelShow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        #endregion

        #region FDS Export & Websocket icons

        internal static System.Drawing.Bitmap exportLarge {
            get {
                object obj = ResourceManager.GetObject("exportLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap selectLarge {
            get {
                object obj = ResourceManager.GetObject("selectLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap websocOpenLarge {
            get {
                object obj = ResourceManager.GetObject("websocOpenLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap websocCloseLarge {
            get {
                object obj = ResourceManager.GetObject("websocCloseLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }


        #endregion


        #region Utils icons

        internal static System.Drawing.Bitmap orbit {
            get {
                object obj = ResourceManager.GetObject("3dorbit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap zoomExt {
            get {
                object obj = ResourceManager.GetObject("zoomExt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap dist {
            get {
                object obj = ResourceManager.GetObject("dist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap area {
            get {
                object obj = ResourceManager.GetObject("area", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap viewTop {
            get {
                object obj = ResourceManager.GetObject("viewTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap viewBottom {
            get {
                object obj = ResourceManager.GetObject("viewBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap viewFront {
            get {
                object obj = ResourceManager.GetObject("viewFront", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap viewBack {
            get {
                object obj = ResourceManager.GetObject("viewBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap viewLeft {
            get {
                object obj = ResourceManager.GetObject("viewLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap viewRight {
            get {
                object obj = ResourceManager.GetObject("viewRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        #endregion


    }
}
